import {
  DataSourceHttpService,
  EntityHttpService,
  EntityNameService,
  HistoricalValueService,
  type AsyncValue,
  type HttpConfig,
  LiveValueService,
  TenantHttpService,
  UserProfileHttpService,
} from 'audako-core';
import type { Observable } from 'rxjs';
import { container } from 'tsyringe';
import { EntitySelectDialogService } from './components/entity-select/entity-select-dialog.service';
import AudakoEntitySelect from './components/entity-select/AudakoEntitySelect.svelte';
import AudakoSelect from './components/select/AudakoSelect.svelte';
import AudakoTenantSelect from './components/tenant-select/AudakoTenantSelect.svelte';
import { tryRegisterService } from './utils/service-functions';
import AudakoMenu from './components/menu/AudakoMenu.svelte';
export { resolveService, tryRegisterService, setGlobalDependencyContainer } from './utils/service-functions';
export type { TextOption } from './shared/components/select/SelectTypes';
export type { MenuItem } from './shared/components/menu/MenuTypes';
// The custom element classes generated by Svelte. `tag` is omitted in each
// component so registration stays explicit, in registerCustomElements below.
// Svelte does not surface the generated `element` static in its component
// types, hence the cast.
function customElementOf(component: unknown): CustomElementConstructor {
  return (component as { element: CustomElementConstructor }).element;
}

export const EntitySelect = customElementOf(AudakoEntitySelect);
export const TenantSelect = customElementOf(AudakoTenantSelect);
export const Select = customElementOf(AudakoSelect);
export const Menu = customElementOf(AudakoMenu);

export { EntitySelectDialogService } from './components/entity-select/entity-select-dialog.service';

export function registerCustomElements() {
  _defineCustomElement('audako-entity-select', EntitySelect);
  _defineCustomElement('audako-tenant-select', TenantSelect);
  _defineCustomElement('audako-select', Select);
  _defineCustomElement('audako-menu', Menu);
}

export function registerCoreServices(httpConfig: HttpConfig, accessToken: AsyncValue<string>): void {
  const entityHttpService = new EntityHttpService(httpConfig, accessToken);

  tryRegisterService(LiveValueService, new LiveValueService(httpConfig, accessToken));
  tryRegisterService(EntityHttpService, entityHttpService);
  tryRegisterService(TenantHttpService, new TenantHttpService(httpConfig, accessToken));
  tryRegisterService(EntityNameService, new EntityNameService(entityHttpService));
  tryRegisterService(DataSourceHttpService, new DataSourceHttpService(httpConfig, accessToken));
  tryRegisterService(EntitySelectDialogService, new EntitySelectDialogService());
  tryRegisterService(HistoricalValueService, new HistoricalValueService(httpConfig, accessToken));
  tryRegisterService(UserProfileHttpService, new UserProfileHttpService(httpConfig, accessToken));
}

function _defineCustomElement(tagName: string, component: any, options?: ElementDefinitionOptions) {
  if (customElements.get(tagName)) {
    return;
  }

  customElements.define(tagName, component, options);
}

// export all from audako-core
export * from 'audako-core';
